export const tag_list = [
  {
    id: 1,
    name: "保湿",
    nayami: "乾燥",
    good_eval: "うるおい",
    bad_eval: "カサカサ",
  },
  {
    id: 2,
    name: "ニキビ・肌荒れ",
    nayami: "ニキビ・肌荒れ",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 3,
    name: "シミ・そばかす",
    nayami: "シミ・そばかす",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 4,
    name: "くま・くすみ",
    nayami: "くま・くすみ",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 5,
    name: "シワ・たるみ",
    nayami: "シワ・たるみ",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 6,
    name: "毛穴",
    nayami: "毛穴",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 7,
    name: "ハリ・弾力",
    nayami: "ハリ・弾力",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
  {
    id: 8,
    name: "美白",
    nayami: "日焼け",
    good_eval: "効果あり",
    bad_eval: "効果なし",
  },
];
