name: prettier

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: Run prettier
        run: npx prettier -l .
